### ISSUE TITLE
Staff Management Screen

### ISSUE THREAD

**Issue by Akarsh654** [UofA-Blueprint/AlzheimerCalgary#48]
staff members should be able to see a list of staff and information about them (similar to client management screen)

![image](https://user-images.githubusercontent.com/56489645/210024535-484d6536-e2ba-4963-8c28-5a3f98012928.png)
https://www.figma.com/file/OON7BdcGohKbI8MaH2jJqH/Sketches?node-id=1%3A15&t=yAwPvtj6O308wpAg-0

**Comment by TonyPhan0505** [comment]
What will the filters be?
